// this hero page is generated by v0.dev

"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import Model from "../components/Model";
import TempOverview from "../components/TempOverview";

export default function SpaceHero() {
  const [stars, setStars] = useState([]);

  useEffect(() => {
    const generateStars = () => {
      const newStars = [];
      for (let i = 0; i < 50; i++) {
        newStars.push({
          id: i,
          x: Math.random() * 100,
          y: Math.random() * 100,
          size: Math.random() * 2 + 1,
        });
      }
      setStars(newStars);
    };

    generateStars();
  }, []);

  return (
    <div
      className={`relative min-h-screen`}
    >
      <TempOverview />
      <Model />
    </div>
  );
}
