// this hero page is generated by v0.dev

"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import { Star } from "lucide-react";

export default function SpaceHero() {
  return (
    <div
      className={`relative min-h-screen flex items-center justify-center overflow-hidden`}
    >
      <div className="relative z-10 text-center px-4">
        <motion.h1
          className="text-[11rem] font-bold mb-4 pointer-events-none"
          initial={{ y: -50, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.8 }}
          style={{
            color: "white",
            textShadow: "4px 4px 8px rgba(0, 0, 0, 0.7)",
          }}
        >
          Explore. Discover. Learn.
        </motion.h1>
        <motion.p
          className="text-xl md:text-2xl text-blue-200 mb-8"
          initial={{ y: 50, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.8, delay: 0.2 }}
        ></motion.p>
        <motion.div
          initial={{ scale: 0 }}
          animate={{ scale: 1 }}
          transition={{ duration: 0.5, delay: 0.5 }}
        >
          <Link
            href="/explore"
            className="inline-block text-white font-bold py-3 px-8 rounded-full text-lg transition-all duration-300 transform hover:scale-110"
          >
            <button className="relative inline-flex h-12 overflow-hidden rounded-full p-[1px] focus:outline-none focus:ring-2 focus:ring-slate-400 focus:ring-offset-2 focus:ring-offset-slate-50">
              <span className="absolute inset-[-1000%] animate-[spin_12s_linear_infinite] bg-[conic-gradient(from_45deg_at_50%_50%,#000000_0%,#4A0E0E_25%,#7D1F1F_50%,#A42C2C_75%,#FF6600_100%)]" />
              <span className="inline-flex h-full w-full cursor-pointer items-center justify-center rounded-full px-3 py-5 text-[1.2rem] transition-all font-medium text-white backdrop-blur-3xl ">
                Come explore the weather!
              </span>
            </button>
          </Link>
        </motion.div>
      </div>
      <motion.div
        className="absolute bottom-10 left-10 text-white"
        animate={{ rotate: 360 }}
        transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
      >
        <Star size={48} />
      </motion.div>
      <motion.div
        className="absolute top-10 right-10 text-white"
        animate={{ rotate: -360 }}
        transition={{ duration: 25, repeat: Infinity, ease: "linear" }}
      >
        <Star size={36} />
      </motion.div>
    </div>
  );
}
