/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./mars/mars.gltf 
Author: Akshat (https://sketchfab.com/shooter24994)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mars-9c7bbc64d8c74acfa9ec344c0fc10e1a
Title: Mars
*/

import React from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export default function Model(props) {
  const { nodes } = useGLTF("/model/mars.gltf");
  const texture = useTexture("/model/textures/Material.002_diffuse.jpeg");
  const material = new THREE.MeshStandardMaterial({ map: texture });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere_Material002_0.geometry}
        material={material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/model/mars.gltf");
